name: 'Actions SemVer Checker'
description: 'Checks the version tags for your action repository to ensure the correct versions will be picked.'
branding:
  icon: 'check-circle'
  color: 'orange'
inputs:
  token:
    description: "GitHub token for API access. If not provided, falls back to GITHUB_TOKEN environment variable."
    required: false
    default: ""
  check-minor-version:
    description: "Configures warnings for minor versions (options: [error, warning, none, true, false], default: error)."
    required: false
    default: "error"
  check-releases:
    description: "Check that for every build version a GitHub Release exists (options: [error, warning, none, true, false], default: error. true maps to error, false maps to none)."
    required: false
    default: "error"
  check-release-immutability:
    description: "Check that releases are immutable and cannot be force-pushed (options: [error, warning, none, true, false], default: error. true maps to error, false maps to none)."
    required: false
    default: "error"
  ignore-preview-releases:
    description: "Ignore preview/pre-release versions when calculating major/minor version tags (options: [true, false], default: true)."
    required: false
    default: "true"
  floating-versions-use:
    description: "Specify whether floating versions (major/minor like v1, v1.0, and latest) should use tags or branches (options: [tags, branches], default: tags)."
    required: false
    default: "tags"
  auto-fix:
    description: "Automatically fix major/minor versions when a build tag is pushed. Requires contents: write permission (options: [true, false], default: false)."
    required: false
    default: "false"
  ignore-versions:
    description: "Comma-separated list of versions to ignore during validation (e.g., 'v1.0.0,v2.0.0'). Useful for skipping legacy or problematic versions."
    required: false
    default: ""
  check-marketplace:
    description: "Check that action.yaml has required marketplace metadata (name, description, branding) and README.md exists (options: [error, warning, none, true, false], default: error)."
    required: false
    default: "error"

runs:
  using: "composite"
  steps:
  - name: "Checking versions..."
    run: |
      & $env:GITHUB_ACTION_PATH/main.ps1
    shell: pwsh
    env:
      inputs: ${{ tojson(inputs) }}
